[package]
name = "server"
version = "0.1.0"
authors = ["Wes White <wtealwhite@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
warp = "0.1.12"
serde_json = "1.0.38"
serde = "1.0.88"
log = "0.4.6"
serde_derive = "1.0.88"
rand = "0.6.5"